workspace = { members = [ "blogs-oops", "minigrep", "my_crates", "server", "src/tests-example"] }
[package]
name = "rust-basics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
