version: "3.1"
services:
  postgres:
    image: postgres:11-alpine
    restart: always
    environment:
      POSTGRES_DB: test-db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5444:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'

